server:
  port: 8181

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: true

spring:
  application.name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://cloud-market.product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1