server:
  port: 0
  servlet:
    context-path: /products

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application.name: cloud-market.product-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cloudmarket
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false