server:
  port: 8100
  servlet:
    context-path: /ui

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application.name: cloud-market.ui-service

feign:
  autoconfiguration:
    jackson:
      enabled=true: